### ISSUE TITLE
Select Midweek Day

### ISSUE THREAD

**Issue by jezzar042015** [jezzar042015/khms#18]
Users can able to select midweek day. If midweek day is selected all week dates are automatically provided in the templates and in the assignment slips

### TASKS
- [ ] create a composable that will compute the date of the given week and weekday
- [ ] provide UI selector
- [ ] save the user preference

### BRANCH

```
git fetch origin
```

```
git checkout 18-select-midweek-day
```
